name: Deploy static content to Pages

on:
  # Se ejecutará cada vez que hagas un push a la rama 'main'
  # (Cámbialo a 'master' si esa es tu rama principal)
  push:
    branches: ['main']

# Otorga los permisos necesarios a GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite guarda el build en la carpeta 'dist' por defecto
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
